name: GitHub Actions Java Test Workflow  # Workflow name
run-name: Running tests on GitHub Actions

on: [push]  # Trigger the workflow on every push

jobs:
  java-test:  # Job name
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and run tests with Maven
        run: mvn clean test
        # 'clean' is added to delete old build artifacts before running tests

  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -la